### ISSUE TITLE
Feedback (II) specific to work at eScience center (e.g. Pull requests, email, feedback after presentation),

### ISSUE THREAD

**Issue by JaroCamphuijsen** [nlesc-sigs/soft-skills-sig#20]
Sources:
- https://docs.gitlab.com/ee/development/code_review.html#best-practices

**Comment by sjvrijn** [comment]
> * https://docs.gitlab.com/ee/development/code_review.html#best-practices

Reminds me of the talk on code reviews in Module 3 of the NLeSC internal training
- https://www.youtube.com/watch?v=0t4_MfHgb_A
- https://www.youtube.com/watch?v=ly86Wq_E18o
