### ISSUE TITLE
Demo about Personal Knowledge Management systems and project/task managers

### ISSUE THREAD

**Issue by ctwhome** [nlesc-sigs/soft-skills-sig#21]
I'd like to share my way of working with PKMs (Personal Knowledge Management) and am eager to see your approaches too. 
I use a combination of Notion.so for projects and task management, and Obsidian.md for the Digital Second Brain (using the Zettelkasten method).

**Comment by CunliangGeng** [comment]
I use Evernote and Zotero (dropbox as storage) for PKM.
And I'm trying Lark (https://www.larksuite.com/), especially its [Bitable](https://www.larksuite.com/en_us/product/bitable?from=hero_section) is amazing!!!

**Comment by PabRod** [comment]
I recently discovered notion.so, and I love it. Obsidian looks like a very tempting alternative. So, I am team @ctwhome! 

However, I don't think it is a good idea to work with two systems.

**Comment by jiskattema** [comment]
I've used [Zim](https://zim-wiki.org/) for a long time. It's comparable to Evernote, but off-line and developer friendly (can do backups via git, has attachements per page etc.)

I sort of migrated to using VIM exclusively, and treat my notes as source code. 
It works for me but i like using the terminal ;)

**Comment by egpbos** [comment]
Used Zim as well, liked it. I migrated to Notion because Zim's macOS support was poor. Notion is great; a bit overkill for my modest needs, but the heavy features are not in the way of my simple weekly logs, so fine.

**Comment by carschno** [comment]
I use plain Markdown in a dedicated, private `notes` repository for a very informal ad-hoc collection of notes in a diary style. Zotero for organizing scientific articles.

I have tried various other things in the past, but have come back to that plain and simple text file format because it is easy to search, to edit anywhere, and to share if desired. The disadvantage is of course that there is no (automatic) linking, but I realised that I never used such features anyway.

**Comment by OleMussmann** [comment]
@carschno [Obsidian](https://obsidian.md/) and [Logseq](https://logseq.com/) (sort of the same, but FLOSS) both use markdown files to store their data. You can use their apps for all the linking magic, templates, pretty rendering, PDF embedding/highlighting/linking, etc. But you can also always edit them with whatever editor you have at hand.

The beauty with automatic linking and searching is that you can have a fresh, clean daily journal where you dump your thoughts and notes. Yet they are fully searchable so you don't lose any information in the noise. Example: with linking and the right filters you can dump TODOs in anywhere, in any file, and they will show up under your respective project pages. 

N.B. Obsidian and Logseq are so similar, you can use them almost interchangeably on the markdown files.

I'm using Logseq and am very happy with it.

**Comment by Peter9192** [comment]
I noticed this conversation and checked out some of the tools. Then I stubled upon Microsoft Loop, which seems kinda similar. Would it be possible to enable this for our organization?

https://www.microsoft.com/en-us/microsoft-loop

![image](https://user-images.githubusercontent.com/17080502/229438800-d9c50644-ed7d-4a9d-adb0-424e8e8b2bd0.png)

**Comment by CunliangGeng** [comment]
Hi Peter,

You could use Loop in our Teams (chat with one person or in a group, not support for Channel chat), see my screen shot

[cid:c70dd745-7c01-4b53-b1b8-3963c2a2cfca]

Cheers,
Cunliang

________________________________

**Comment by jiqicn** [comment]
Just found this interesting thread and wonder if anyone uses [Joplin](https://github.com/laurent22/joplin) like me. I have used it for years and enjoy it very much. It is an open-sourced software available on nearly all platforms (it even has a terminal version, check the screenshot below). The advantages of Joplin include but are not limited to: markdown and vim support, links, attachments, encrypted synchronization, read-it-later, and various plugins.

![image](https://user-images.githubusercontent.com/92043159/229562352-53c38180-2df1-4acd-93fd-915be06dea19.png)

**Comment by lopeztarifa** [comment]
Hi all, 

Thanks for contributing to this thread, we are planning a session on the topic for May 4th with some PKMs demos. We have Jesús already on board, would you like to showcase yours? 

Thanks

**Comment by carschno** [comment]
> Thanks for contributing to this thread, we are planning a session on the topic for May 4th with some PKMs demos. We have Jesús already on board, would you like to showcase yours?

I would like to, but I will be travelling during that entire week, unfortunately.

**Comment by egpbos** [comment]
I'm on holiday next week, sorry.

**Comment by bvreede** [comment]
Same here :(
